---
- name: PACKAGE_MANAGER - Ensure apt utilities are installed
  ansible.builtin.package:
    name:
      - apt-utils
      - apt-transport-https
      - ca-certificates
      - apt-file
    state: present
