---
- name: Configure apt repositories
  ansible.builtin.include_tasks: configure.yml

- name: Install base apt packages
  ansible.builtin.include_tasks: install.yml

- name: Configure unattended upgrades
  ansible.builtin.include_tasks: upgrades.yml
  when: package_manager_enable_auto_upgrades | bool
