---
- name: Install unattended-upgrades packages
  ansible.builtin.package:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present
    update_cache: true

- name: Configure unattended-upgrades origins pattern
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/51odem-origins
    content: |
      Unattended-Upgrade::Origins-Pattern {
              "origin=Debian,codename=${distro_codename}-updates";
      };
    owner: root
    group: root
    mode: "0644"

- name: Configure apt periodic update and upgrade
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    owner: root
    group: root
    mode: "0644"

- name: Enable and start unattended-upgrades service
  ansible.builtin.systemd:
    name: unattended-upgrades.service
    enabled: true
    state: started

- name: Enable and start apt-daily-upgrade timer
  ansible.builtin.systemd:
    name: apt-daily-upgrade.timer
    enabled: true
    state: started
