---
namespace: odem
name: os
version: 0.3.1
readme: README.md
authors:
  - foo <bar@baz.com>
description: Operating system initialization — package management, system settings, core tools
license:
  - GPL-3.0-or-later
tags:
  - linux
  - os
  - infrastructure
  - odem
repository: https://github.com/my-perfect-system/odem-os
documentation: https://github.com/my-perfect-system/odem-os
homepage: https://github.com/my-perfect-system/odem-os
issues: https://github.com/my-perfect-system/odem-os/issues
build_ignore:
  - .git
  - .github
  - .gitignore
  - .ansible-lint
  - .yamllint
  - .venv
  - tests
  - "*.tar.gz"
  - .ansible
dependencies:
  odem.base: ">=0.1.0"
  ansible.posix: ">=1.0.0"
