---
galaxy_info:
  author: foo <bar@baz.com>
  description: "Configure system locale, keyboard, and timezone"
  min_ansible_version: "2.16.0"
  license: GPL-3.0-or-later
  platforms:
    - name: Debian
      versions:
        - trixie
  galaxy_tags:
    - debian
    - debian13
    - trixie
    - locale
    - timezone
    - keyboard
    - console
    - odem-debian
dependencies:
  - role: odem.base.assert_debian13
