---

# Feature toggles — naming pattern: <rolename>_enable_<feature>

package_manager_enable_auto_upgrades: true

package_manager_enable_repos_main: true

package_manager_enable_repos_updates: true

package_manager_enable_repos_backports: true

package_manager_enable_repos_security: true

package_manager_enable_components_contrib: true

package_manager_enable_components_non_free: true

package_manager_enable_components_non_free_firmware: true

package_manager_enable_deb_src: true

# Regular configuration

package_manager_upgrade: dist
