---
- name: Install build toolchain packages
  ansible.builtin.package:
    name:
      - gcc
      - gdb
      - lldb
      - build-essential
      - check
      - flex
      - bison
      - automake
    state: present
