---
- name: Install modern file manager alternatives
  ansible.builtin.package:
    name:
      - bat
      - eza
      - tree
      - ncdu
      - entr
      - ripgrep
      - zoxide
    state: present
