---
- name: Install network diagnostic tools
  ansible.builtin.package:
    name:
      - net-tools
      - bind9-dnsutils
      - bridge-utils
      - iptables
      - tcpdump
      - traceroute
      - netcat-traditional
      - nmap
    state: present
