---
- name: Install console-setup package
  ansible.builtin.package:
    name: console-setup
    state: present

- name: Write /etc/default/console-setup
  ansible.builtin.copy:
    dest: /etc/default/console-setup
    content: |
      ACTIVE_CONSOLES="/dev/tty[1-6]"
      CHARMAP="{{ system_settings_console_charset }}"
      CODESET="{{ system_settings_console_codeset }}"
      FONTFACE="{{ system_settings_console_fontface }}"
      FONTSIZE="{{ system_settings_console_fontsize }}"
      VIDEOMODE=
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reconfigure console-setup
    - Restart console-setup

- name: Enable and start console-setup service
  ansible.builtin.systemd:
    name: console-setup.service
    enabled: true
    state: started
