---
- name: Configure locale
  ansible.builtin.include_tasks: locale.yml

- name: Configure keyboard
  ansible.builtin.include_tasks: keyboard.yml

- name: Configure console
  ansible.builtin.include_tasks: console.yml

- name: Configure time and timezone
  ansible.builtin.include_tasks: time.yml
