---
- name: Read current system timezone
  ansible.builtin.command: timedatectl show --property=Timezone --value
  register: system_settings_current_timezone
  changed_when: false
  check_mode: false

- name: Set system timezone if changed
  ansible.builtin.command: timedatectl set-timezone {{ system_settings_timezone }}
  when: system_settings_current_timezone.stdout != system_settings_timezone
  changed_when: true

- name: Install chrony package
  ansible.builtin.package:
    name: chrony
    state: present

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Enable and start chrony service
  ansible.builtin.systemd:
    name: chrony.service
    enabled: true
    state: started
